// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'final_report_repository.dart';
export 'final_report_service.dart';
export 'final_report_viewmodel.dart';